### ISSUE TITLE
Not able to run a tkinter program

### ISSUE THREAD

**Issue by yijianli-autra** [astral-sh/python-build-standalone#146]
I am using the bazel/rules_python to compile our python code. 
according to the configuration, we are using the 
cpython-3.9.13+20220802-x86_64-unknown-linux-gnu-install_only.tar.gz as our python interpreter.
But as we are using the Tkinter, there is a segment fault during the runtime.
the code
```python
import faulthandler
faulthandler.enable()

import tkinter
from tkinter.constants import *
tk = tkinter.Tk()
frame = tkinter.Frame(tk, relief=RIDGE, borderwidth=2)
frame.pack(fill=BOTH,expand=1)
label = tkinter.Label(frame, text="Hello, World")
label.pack(fill=X, expand=1)
button = tkinter.Button(frame,text="Exit",command=tk.destroy)
button.pack(side=BOTTOM)
tk.mainloop()
```

the stack trace
```
/tmp/python_interpreter_x86_64-unknown-linux-gnu ❯ ./bin/python3.9 tkinter_test.py                                                                                                                                                                                            
Fatal Python error: Segmentation fault

Current thread 0x00007fe29108ef40 (most recent call first):
  File "/tmp/python_interpreter_x86_64-unknown-linux-gnu/lib/python3.9/tkinter/__init__.py", line 2572 in __init__
  File "/tmp/python_interpreter_x86_64-unknown-linux-gnu/lib/python3.9/tkinter/__init__.py", line 3148 in __init__
  File "/tmp/python_interpreter_x86_64-unknown-linux-gnu/tkinter_test.py", line 9 in <module>
[1]    55139 segmentation fault (core dumped)  ./bin/python3.9 tkinter_test.py
```

according to other tickets, seems the python interpreter is already linked to the Tkinter. 

# Update
I was trying to use the debug version to know what happened in the core dump. but it is very strange that I am able to run this with python3.9d. it is very weird.

**Comment by indygreg** [comment]
Thanks for the report.

Can confirm this fails on the latest 20221107 distributions. The x86_64-unknown-linux-gnu distribution fails for me on the `>>> label = tkinter.Label(frame, text="Hello, World")` line:

```
>>> label = tkinter.Label(frame, text="Hello, World")
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
Fatal Python error: Aborted

Current thread 0x00007f7f676b5c40 (most recent call first):
  File "/home/gps/src/python-build-standalone/dist/python/lib/python3.9/tkinter/__init__.py", line 2572 in __init__
  File "/home/gps/src/python-build-standalone/dist/python/lib/python3.9/tkinter/__init__.py", line 3148 in __init__
  File "<stdin>", line 1 in <module>
Aborted (core dumped)
```

This program works with other Python builds on my system. So something is amiss.

The `xcb` warnings point to a potential interaction with that library. I reckon we're missing a configure flag somewhere in the X11 libraries which results in something using a non-standard config. tk and/or CPython is probably making assumptions about some X library config that aren't true.

There's possibly an upstream bug or two to report in here somewhere. But I don't know what until root cause is understood.

**Comment by indygreg** [comment]
Here's an excerpt from libxcb's configure:

```
Package: libxcb 1.13.1

  Configuration
    XDM support.........: no
    sendmsg fd passing..: yes
    Build unit tests....: no
      with html results.: no
    XCB buffer size.....: 16384

  X11 extensions
    Composite...........: yes

  Package: libxcb 1.13.1

  Configuration
    XDM support.........: no
    sendmsg fd passing..: yes
    Build unit tests....: no
      with html results.: no
    XCB buffer size.....: 16384

  X11 extensions
    Composite...........: yes
Damage..............: yes
    Dpms................: yes
    Dri2................: yes
    Damage..............: yes
    Dpms................: yes
    Dri2................: yes
Dri3................: yes
    GenericEvent........: no
    Glx.................: yes
    Randr...............: yes
    Record..............: yes
    Render..............: yes
    Dri3................: yes
    GenericEvent........: no
    Glx.................: yes
    Randr...............: yes
    Record..............: yes
    Render..............: yes
Resource............: yes
    Screensaver.........: yes
    Resource............: yes
    Screensaver.........: yes
selinux.............: no
    Shape...............: yes
    Shm.................: yes
    Sync................: yes
    Xevie...............: no
    Xfixes..............: yes
    Xfree86-dri.........: yes
    selinux.............: no
    Shape...............: yes
    Shm.................: yes
    Sync................: yes
    Xevie...............: no
    Xfixes..............: yes
    Xfree86-dri.........: yes
xinerama............: yes
    xinput..............: yes
    xkb.................: yes
    xprint..............: no
    xtest...............: yes
    xinerama............: yes
    xinput..............: yes
    xkb.................: yes
    xprint..............: no
    xtest...............: yes
xv..................: yes
    xvmc................: yes

  Used CFLAGS:
    CPPFLAGS............: -fvisibility=hidden -fPIC
    CFLAGS..............: -fvisibility=hidden -fPIC

  Installation:
    Prefix..............: /tools/deps
    xv..................: yes
    xvmc................: yes

  Used CFLAGS:
    CPPFLAGS............: -fvisibility=hidden -fPIC
    CFLAGS..............: -fvisibility=hidden -fPIC

  Installation:
    Prefix..............: /tools/deps
```

I have no clue how to interpret any of it though.

(I wish all configure scripts gave you concise reports of important metadata like this!)

**Comment by indygreg** [comment]
And from `libx11`:

```
11 will be built with the following settings:
 Loadable i18n module support:            no
 Loadable xcursor library support:        yes
 Threading support:                       yes
 Use Threads safe API:                    yes
 Threads stubs in libX11:                 no
 XCMS:                                    yes
 Internationalization support:            yes
 XF86BigFont support:                     yes
 XKB support:                             yes
 XLOCALEDIR environment variable support: yes
 Compose table cache enabled:             yes
 Functional specs building enabled:       yes

X11 will be built with the following settings:
 Loadable i18n module support:            no
 Loadable xcursor library support:        yes
 Threading support:                       yes
 Use Threads safe API:                    yes
 Threads stubs in libX11:                 no
 XCMS:                                    yes
 Internationalization support:            yes
 XF86BigFont support:                     yes
 XKB support:                             yes
 XLOCALEDIR environment variable support: yes
 Compose table cache enabled:             yes
 Functional specs building enabled:       yes
```

`Threads stubs in libX11` seems potentially relevant.

**Comment by indygreg** [comment]
OK. We compile tk with `-DTCL_THREADS=1`. And we see some code in tk calling `XInitThreads()` (it is the only caller of `XInitThreads()` I found outside libX11 source, so I think this is the only relevant caller).

However, that code in tk (`unix/tkUnixEvent.c`) is protected behind an `#if 0 && defined(XKEYCODETOKEYSYM_IS_DEPRECATED) && defined(TCL_THREADS)`. That will never be true. So we never call `XInitThreads()`.

I think the problem here is we build tcl/tk with support for threads? Is this somehow different from how the entire world builds tcl/tk?

Note that I enabled threads in commit 169bdadd6ed2de0d2940ba600c73af2709608aa9. But sadly didn't leave any context. (Very uncharacteristic of me!) Commits around it were part of enabling tcl/tk to build on macOS. I wonder if I enabled threads for a reason or just saw they weren't enabled and figured enabling threads was a good idea?

**Comment by indygreg** [comment]
Hmmm. `/usr/lib/x86_64-linux-gnu/tclConfig.sh` and `/usr/lib/x86_64-linux-gnu/tkConfig.sh` on my machine (Ubuntu 22.04) says we built with `TCL_THREADS=1`. I wonder why my machine's tk is working but this one isn't...

**Comment by Edward-Knight** [comment]
To add on to the debugging - I cannot reproduce when using xvfb in Docker or otherwise

**Comment by dae** [comment]
Could it perhaps be related to the change mentioned here? https://github.com/indygreg/python-build-standalone/issues/95#issuecomment-1127021925

**Comment by jplumail** [comment]
After a git bisect testing against OP code, I found that [this commit](https://github.com/indygreg/python-build-standalone/commit/924693c91331426d9909649e6bb5cdcae8446784) is the first bad commit.
I have no idea about how to fix this though !

**Comment by ck-google** [comment]
I am running into this issue. Has anyone found a workaround for this?

**Comment by krabhi1** [comment]
hey , please solve this issue!

**Comment by zanieb** [comment]
Just confirming this is still reproducible after upgrading tcl/tk (#495)

```
❯ uv version
uv 0.5.19
❯ uv python list --show-urls | grep cpython-3.9
cpython-3.9.21-linux-x86_64-gnu                   https://github.com/astral-sh/python-build-standalone/releases/download/20250115/cpython-3.9.21%2B20250115-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz
❯ uv python install --reinstall 3.9 3.13
Installed 2 versions in 3.60s
 ~ cpython-3.9.21-linux-x86_64-gnu
 ~ cpython-3.13.1-linux-x86_64-gnu

❯ uv run -v -p 3.9 script.py
DEBUG uv 0.5.19
DEBUG No project found; searching for Python interpreter
DEBUG Searching for Python 3.9 in virtual environments, managed installations, or search path
DEBUG Searching for managed installations at `/home/zb/.local/share/uv/python`
DEBUG Skipping incompatible managed installation `cpython-3.13.1-linux-x86_64-gnu`
DEBUG Skipping incompatible managed installation `cpython-3.12.8-linux-x86_64-gnu`
DEBUG Found managed installation `cpython-3.9.21-linux-x86_64-gnu`
DEBUG Found `cpython-3.9.21-linux-x86_64-gnu` at `/home/zb/.local/share/uv/python/cpython-3.9.21-linux-x86_64-gnu/bin/python3.9` (managed installations)
DEBUG Using Python 3.9.21 interpreter at: /home/zb/.local/share/uv/python/cpython-3.9.21-linux-x86_64-gnu/bin/python3.9
DEBUG Running `python script.py`
[xcb] Unknown sequence number while appending request
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
python3.9: xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
Fatal Python error: Aborted

Current thread 0x00007d0a0c6d6740 (most recent call first):
  File "/home/zb/.local/share/uv/python/cpython-3.9.21-linux-x86_64-gnu/lib/python3.9/tkinter/__init__.py", line 2572 in __init__
  File "/home/zb/.local/share/uv/python/cpython-3.9.21-linux-x86_64-gnu/lib/python3.9/tkinter/__init__.py", line 3148 in __init__
  File "/fast/workspace/python-build-standalone/script.py", line 9 in <module>
DEBUG Command exited with signal: Some(6)

❯ uv run -v -p 3.13 script.py
DEBUG uv 0.5.19
DEBUG No project found; searching for Python interpreter
DEBUG Searching for Python 3.13 in virtual environments, managed installations, or search path
DEBUG Searching for managed installations at `/home/zb/.local/share/uv/python`
DEBUG Found managed installation `cpython-3.13.1-linux-x86_64-gnu`
DEBUG Found `cpython-3.13.1-linux-x86_64-gnu` at `/home/zb/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/bin/python3.13` (managed installations)
DEBUG Using Python 3.13.1 interpreter at: /home/zb/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/bin/python3.13
DEBUG Running `python script.py`
[xcb] Unknown sequence number while appending request
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
python3.13: xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
Fatal Python error: Aborted

Current thread 0x00007df5d281d740 (most recent call first):
  File "/home/zb/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/lib/python3.13/tkinter/__init__.py", line 2772 in __init__
  File "/home/zb/.local/share/uv/python/cpython-3.13.1-linux-x86_64-gnu/lib/python3.13/tkinter/__init__.py", line 3361 in __init__
  File "/fast/workspace/python-build-standalone/script.py", line 9 in <module>
DEBUG Command exited with signal: Some(6)
```

**Comment by f1sherb0y** [comment]
Also met the same issue for this simple program (ubuntu 24.0.1 LTS, amd64):

`import tkinter as tk


def show_window(message):
    """Displays a simple tkinter window with a message."""
    root = tk.Tk()
    root.withdraw()  # Hide the root window initially

    window = tk.Toplevel(root)
    window.title("Simple Window")

    label = tk.Label(window, text=message, padx=20, pady=10)
    label.pack()

    ok_button = tk.Button(window, text="OK", command=window.destroy)
    ok_button.pack()

    window.focus_set()  # Request focus for the newly opened window
    window.grab_set()  # Make it modal

    root.wait_window(window)
    root.destroy()
    # window.destroy() # Destroy Toplevel does not actually exit the program.


if __name__ == "__main__":
    message_to_show = "This is a simple window!"
    show_window(message_to_show)
`

output:
`    
(test) fisherboy@laptop$ cat ./.python-version
3.12
(test) fisherboy@laptop$ cat ./pyproject.toml
[project]
name = "meme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ ]                  
(test) fisherboy@laptop$ python debug.py
[xcb] Unknown sequence number while appending request
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
Aborted (core dumped)

**Comment by linde12** [comment]
Also encountering this, using Arch (btw), but it is working with python 3.8 and 3.13 (none of which i can use in my project)

`test.py`:
```python
import tkinter


def main():
    root = tkinter.Tk()
    button = tkinter.Button(root, text="Click Me")
    button.pack(padx=20, pady=20)
    root.mainloop()


if __name__ == "__main__":
    main()
```

- `uv run -p 3.8 test.py` - OK
- `uv run -p 3.9 test.py` - Fail
- `uv run -p 3.10 test.py` - Fail
- `uv run -p 3.11 test.py` - Fail
- `uv run -p 3.12 test.py` - Fail
- `uv run -p 3.13 test.py` - OK

**Comment by rezzubs** [comment]
> Also encountering this, using Arch (btw), but it is working with python 3.8 and 3.13 (none of which i can use in my project)

See if `--python-preference only-managed` changes this. For me the system version of 3.13 is okay but the managed one fails (also on arch, in a distrobox though).

**Comment by linde12** [comment]
@rezzubs Ah!

Aha, `uv run -p 3.13 --python-preference only-managed test.py` does not work either, but with `-p 3.8` it worked.

![Image](https://github.com/user-attachments/assets/338bf872-ed14-4208-92d1-609236826708)

No tcl error (which i've gotten before and worked around using `TCL_LIBRARY` env var) but reinstalling python 3.8 via `uv python uninstall 3.8` and then just running `uv run -p 3.8 --python-preference only-managed test.py` again broke it.

Perhaps i had a version of py 3.8 that was working, but after uninstalling and letting uv grab the latest 3.8 release it breaks. So basically only my system python & older (?) releases of [python-build-standalone](https://github.com/astral-sh/python-build-standalone) are working? :-(

**Comment by Asachoo** [comment]
I encountered a similar issue with `tkinter` when setting up a new virtual environment using `uv`. If the error message is:
```bash
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    main()
  File "test.py", line 5, in main
    root = tkinter.Tk()
  File "/var/home/rezzubs/.local/share/uv/python/cpython-3.8.20-linux-x86_64-gnu/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /tools/deps/lib/tcl8.6 /var/home/rezzubs/dev/tkinter-test/.venv/lib/tcl8.6 /var/home/rezzubs/dev/tkinter-test/lib/tcl8.6 /var/home/rezzubs/dev/tkinter-test/.venv/library /var/home/rezzubs/dev/tkinter-test/library /var/home/rezzubs/dev/tkinter-test/tcl8.6.12/library /var/home/rezzubs/dev/tcl8.6.12/library



This probably means that Tcl wasn't installed properly.
```
This issue can be resolved by setting the `TCL_LIBRARY` and `TK_LIBRARY` environment variables, as suggested in https://github.com/astral-sh/uv/issues/7036#issuecomment-2440145724.

However, if the error message is:
```bash
[xcb] Unknown sequence number while appending request
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
python3: xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
```
I have not yet found a solution for this particular error.

**Comment by Mike710Shine** [comment]
I solved the error that i don't let uv manage the python Version i managed it with pyenv. Install for example 3.12 with pyenv run uv venv in the Projekt what is based on 3.12 and it works. When i let uv managed the python version an i install the version 3.12 from uv i get the xcb error.

**Comment by Mike710Shine** [comment]
Since managing Python with uv doesn't work when using tkinter, I decided to manage the Python versions with pyenv and that works quite well.I

**Comment by linde12** [comment]
@Mike710Shine interestingly i tried this on my laptop and got the same error, but now when i try on my desktop it works. I must've done something wrong. Are you still able to manage dependencies with uv or you completely went with pyenv?

**Comment by Mike710Shine** [comment]
@linde12 i manage my dependencies with uv but my python installations with chocolatey on windows and on linux with pyenv. First i install pyenv set the string for the fish shell in the config and then i do the rest with uv and it works.

**Comment by Mike710Shine** [comment]
I know that pyenv build every python direct from source when i'm right. Maybe it's a good solution that uv has an flag to avoid the installation from the builded source form astral an build it on it's own like pyenv. Maybe this not ends in an not runable tkinter project because i love uv but that i can't run tkinter project when uv manage the python versions only when i use the newest one it is very uncool.

**Comment by Mike710Shine** [comment]
Here some screenshots.

![Image](https://github.com/user-attachments/assets/6f1168bd-7d89-4370-a628-9b1676cbcc66)

![Image](https://github.com/user-attachments/assets/458e8621-5388-4494-a3d0-30886be7da25)

![Image](https://github.com/user-attachments/assets/1818a4ec-7bf8-4fab-9901-22b73153a62a)

**Comment by astrojuanlu** [comment]
This probably isn't very useful but the error seems to come from here

https://github.com/mirror/libX11/blob/ff8706a5eae25b8bafce300527079f68a201d27f/src/xcb_io.c#L146-L159

last commit on that file is precisely clarifying the error message we're seeing https://github.com/mirror/libX11/commit/da97120f2322882a17f14e5d7da00c1e772679e8

The maintainers of python-build-standalone have already acknowledged the bug (https://github.com/astral-sh/python-build-standalone/issues/146#issuecomment-2594146561) so it's down to someone to find out what's wrong about https://github.com/astral-sh/python-build-standalone/blob/main/cpython-unix/build-libX11.sh, or libX11 itself, or Tcl/Tk, or CPython... probably some very deep debugging required, a bit of luck, or both.

**Comment by indygreg** [comment]
The bug almost certainly reduces to loading multiple versions of a library into a binary or there being a mismatch between the build and run time versions.

**Comment by zanieb** [comment]
I fixed this with ff0ee27d1b2fb55d134efb19c0c0440fcf54e14f but am not happy with the approach

cc @geofft perhaps you have an idea of how to make that better? I think, at the very least, we should generate the contents replacing the `ALL` exclusion.

**Comment by zanieb** [comment]
Let's keep conversation here focused on the specific bug here rather than uv Python installation behaviors / pyenv / etc. please.

**Comment by linde12** [comment]
> I fixed this with [ff0ee27](https://github.com/astral-sh/python-build-standalone/commit/ff0ee27d1b2fb55d134efb19c0c0440fcf54e14f) but am not happy with the approach
> 
> cc [@geofft](https://github.com/geofft) perhaps you have an idea of how to make that better? I think, at the very least, we should generate the contents replacing the `ALL` exclusion.

That commit was included in the latest release, or am i missing something? Because the error still happens with when i install 3.12.9 with uv.

`uv` grabs python from `20250212` release via https://github.com/astral-sh/python-build-standalone/releases/download/20250212/cpython-3.12.9%2B20250212-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz

```fish
~ via 🐍 v3.13.2
❯ uv python install --verbose 3.12.9
DEBUG uv 0.6.4
DEBUG Acquired lock for `.local/share/uv/python`
DEBUG No installation found for request `Python 3.12.9`
DEBUG Found download `cpython-3.12.9-linux-x86_64-gnu` for request `Python 3.12.9`
DEBUG Using request timeout of 30s
Downloading cpython-3.12.9-linux-x86_64-gnu (20.3MiB)
DEBUG Downloading https://github.com/astral-sh/python-build-standalone/releases/download/20250212/cpython-3.12.9%2B20250212-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz to temporary location: /home/linde/.local/share/uv/python/.temp/.tmpGoaoXR
DEBUG Extracting cpython-3.12.9%2B20250212-x86_64-unknown-linux-gnu-install_only_stripped.tar.gz
 Downloaded cpython-3.12.9-linux-x86_64-gnu
DEBUG Moving /home/linde/.local/share/uv/python/.temp/.tmpGoaoXR/python to .local/share/uv/python/cpython-3.12.9-linux-x86_64-gnu
DEBUG Skipping installation of Python executables, use `--preview` to enable.
Installed Python 3.12.9 in 4.48s
 + cpython-3.12.9-linux-x86_64-gnu
DEBUG Released lock at `/home/linde/.local/share/uv/python/.lock`

~ via 🐍 v3.13.2 took 4s
❯ uv run -p 3.12.9 --python-preference only-managed test.py
[xcb] Unknown sequence number while appending request
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
python3.12: xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
```

**Comment by charliermarsh** [comment]
No, I don't think that commit has been merged. It's on an open branch.

**Comment by linde12** [comment]
> No, I don't think that commit has been merged. It's on an open branch.

Ah, then it makes sense. Thanks!

**Comment by rnwolf** [comment]
Someone commented that this was not a problem on MS-Windows.
I wanted to say I get the what seems to be the problem on MS-Windows.

```
❯ uvx --version
uv-tool-uvx 0.6.11 (0632e24d1 2025-03-30)
```


 ```
❯ uvx .\my_tkinter_app-0.1.2-py3-none-any.whl
Installed 3 packages in 1.22s
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\rnwol\AppData\Local\uv\cache\archive-v0\u-Iv1TOsu8C9Esopv3qX4\Scripts\my-tkinter-app.exe\__main__.py", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\rnwol\AppData\Local\uv\cache\archive-v0\u-Iv1TOsu8C9Esopv3qX4\Lib\site-packages\my_tkinter_app\app.py", line 24, in main
    controller = MainController()
  File "C:\Users\rnwol\AppData\Local\uv\cache\archive-v0\u-Iv1TOsu8C9Esopv3qX4\Lib\site-packages\my_tkinter_app\controller\main_controller.py", line 7, in __init__
    self.view = MainView(self)
                ~~~~~~~~^^^^^^
  File "C:\Users\rnwol\AppData\Local\uv\cache\archive-v0\u-Iv1TOsu8C9Esopv3qX4\Lib\site-packages\my_tkinter_app\view\main_view.py", line 5, in __init__
    super().__init__()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\rnwol\AppData\Roaming\uv\python\cpython-3.13.0-windows-x86_64-none\Lib\tkinter\__init__.py", line 2459, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/rnwol/AppData/Roaming/uv/python/cpython-3.13.0-windows-x86_64-none/lib/tcl8.6 C:/Users/rnwol/AppData/Roaming/uv/python/lib/tcl8.6 C:/Users/rnwol/AppData/Roaming/uv/lib/tcl8.6 C:/Users/rnwol/AppData/Roaming/uv/python/library C:/Users/rnwol/AppData/Roaming/uv/library C:/Users/rnwol/AppData/Roaming/uv/tcl8.6.12/library C:/Users/rnwol/AppData/Roaming/tcl8.6.12/library
```

But if I specify the python version installed from https://www.python.org/downloads/
```
❯ uvx -p "C:\Python313\python.exe" .\my_tkinter_app-0.1.3-py3-none-any.whl
Installed 3 packages in 1.25s
```

The application is a basic TKinter app.  [https://github.com/rnwolf/my_tkinter_app](https://github.com/rnwolf/my_tkinter_app)

**Comment by alexis-massa** [comment]
Hello,  Unsure if this is the right issue to comment on apologies in advance if it isn't.
I've been reading around those threads for an hour and can't seem to fix using python 3.13.
Using python 3.12 does work.

**OS**: Ubuntu 24.04
**uv**: 0.6.14
**python**: 3.13.3
**tcl**: 8.6

I did try to `uv python install --reinstall 3.13`.

```
$ uv run -p 3.13 test.py # <- Does not work
[xcb] Unknown sequence number while appending request
[xcb] You called XInitThreads, this is not your fault
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:157: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.

$ uv run -p 3.12 test.py  # <- Works fine
Using CPython 3.12.3 interpreter at: /usr/bin/python3.12
Removed virtual environment at: .venv
Creating virtual environment at: .venv
```

The test.py script simply calls tkinter's _test():
```py
import tkinter
tkinter._test()
```

**Comment by rezzubs** [comment]
> I did try to `uv python install --reinstall 3.13`.

Remove the virtual environment and install python with some other tool like pyenv. Then use

```
uv run -p 3.13 --no-managed-python
```

Future runs will use the version from the newly created venv I'm pretty sure.

**Comment by reteps** [comment]
I was able to repro this as well with `python-build-standalone` on `3.10 - 3.13`.

Repro

`main.py`

```python3
import os
import tkinter
worker_pid = os.fork()
if worker_pid == 0:
    import subprocess
    subprocess.run(["/usr/bin/whoami"], capture_output=True, encoding="utf-8", check=True)
else:
    pid, status = os.waitpid(worker_pid, 0)
    if not os.WIFEXITED(status):
        print(f"ungraceful exit with signal {os.WTERMSIG(status)}")
```

With a managed python:

```
rm -rf .venv pyproject.toml
uv init --python 3.13
uv venv --python-preference only-managed
source .venv/bin/activate
python3 main.py
```

Behavior - crash:

```
ungraceful exit with signal 5
```

With a system python installed via `brew install python@3.13`

```
rm -rf .venv pyproject.toml
uv init --python 3.13
uv venv --python-preference only-system
source .venv/bin/activate
python3 main.py
```

Expected behavior (no crash)

```
Traceback (most recent call last):
  File "/Users/peter/work/tkinter-repro/main.py", line 2, in <module>
    import tkinter
  File "/opt/homebrew/Cellar/python@3.13/3.13.4/Frameworks/Python.framework/Versions/3.13/lib/python3.13/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by geofft** [comment]
I believe this is fixed by one of the changes in #676, specifically `libX11: ./configure --disable-loadable-xcursor`, which is being released soon.

It turns out that X11 has code (in src/CrGlCur.c), even when statically linked, to attempt to dynamically load a libXcursor.so and use it. If your system has one, it's probably linking the system version of libX11.so, and now an object created by our build of libX11 is being used by the system's build, which goes poorly. I think this explains why this bisected to 924693c91331426d9909649e6bb5cdcae8446784 (before that change, the functions in our build of libX11 would get used) and why it doesn't happen on certain Docker containers or environments.

The issue that @Asachoo and @rnwolf reported about "Can't find a usable init.tcl" is unrelated. I would have expected it to be solved by #421 - can you please confirm when your Python was built? What's the date printed when the REPL starts, or in `sys.version`? If you're still seeing it on current builds, let's open a separate issue for that one.

**Comment by geofft** [comment]
Hi all - I believe this issue (segmentation faults, aborts in Xcb, etc.) should be resolved in the latest release.

For uv users, make sure you're using uv 0.8.8 and have updated your local Python versions:

```
uv self update
uv python upgrade --reinstall
```

[edited to simplify the command above with uv 0.8.8]

For other python-build-standalone users, please make sure you're using today's release ([20250808](https://github.com/astral-sh/python-build-standalone/releases/20250808)).

Please try it out and let me know if there are remaining issues.

(By the way, if anyone sees _new_ bugs from this, please first open a new issue and at-mention me, and then use `uvx uv@0.8.6 python install --reinstall --no-bin 3.13.6` etc. to roll back to yesterday's 20250807 release. I don't expect this to break anything, but it is a pretty significant change in what's in the Python distributions and how things are linked, so it might have some unexpected side effects.)

As mentioned above I think the "Can't find a usable init.tcl" problem was solved previously in December... but please try the same update instructions and see if it's fixed :)

**Comment by reteps** [comment]
@geofft My repro still doesn't work:

This is my setup command to ensure I am running the latest everything.

```sh
uv self update && uv python install --reinstall --no-bin 3.13.6 && \
uv init --python 3.13 && uv venv --python-preference only-managed --clear && source .venv/bin/activate && python3 main.py
```

I'm on an `Apple M4 Pro` + `15.4.1 (24E263)`.

**Comment by geofft** [comment]
@reteps I can reproduce that on my Mac laptop, but that's a wholly different issue from i think the one that people were discussing in this thread, regarding xcb, which is only used on Linux. I opened #758 to track it, thanks for the report and reproducer!

(Also note that your comment above says the expected behavior is that the `_tkinter` module is unavailable. if that's the behavior you want, you can just delete it. I am guessing what you mean is that the expected behavior is that the code imports `_tkinter` successfully and runs without crashing, which is what the system version of Python seems to do.)

**Comment by linde12** [comment]
> Hi all - I believe this issue (segmentation faults, aborts in Xcb, etc.) should be resolved in the latest release.
> 
> For uv users, make sure you're using uv 0.8.8 and have updated your local Python versions:
> 
> ```
> uv self update
> uv python upgrade --reinstall
> ```
> 
> [edited to simplify the command above with uv 0.8.8]
> 
> For other python-build-standalone users, please make sure you're using today's release ([20250808](https://github.com/astral-sh/python-build-standalone/releases/20250808)).
> 
> Please try it out and let me know if there are remaining issues.
> 
> (By the way, if anyone sees _new_ bugs from this, please first open a new issue and at-mention me, and then use `uvx uv@0.8.6 python install --reinstall --no-bin 3.13.6` etc. to roll back to yesterday's 20250807 release. I don't expect this to break anything, but it is a pretty significant change in what's in the Python distributions and how things are linked, so it might have some unexpected side effects.)
> 
> As mentioned above I think the "Can't find a usable init.tcl" problem was solved previously in December... but please try the same update instructions and see if it's fixed :)

Confirmed! Tried 3.11 & 3.12 - verified that my program still was crashing before doing the reinstall but after upgrading with `--reinstall` it works (although there is some issues with corner rounding on elements, but not necessarily related to this issue). Awesome! 🙏

**Comment by xarthurx** [comment]
> > Hi all - I believe this issue (segmentation faults, aborts in Xcb, etc.) should be resolved in the latest release.
> > For uv users, make sure you're using uv 0.8.8 and have updated your local Python versions:
> > ```
> > uv self update
> > uv python upgrade --reinstall
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [edited to simplify the command above with uv 0.8.8]
> > For other python-build-standalone users, please make sure you're using today's release ([20250808](https://github.com/astral-sh/python-build-standalone/releases/20250808)).
> > Please try it out and let me know if there are remaining issues.
> > (By the way, if anyone sees _new_ bugs from this, please first open a new issue and at-mention me, and then use `uvx uv@0.8.6 python install --reinstall --no-bin 3.13.6` etc. to roll back to yesterday's 20250807 release. I don't expect this to break anything, but it is a pretty significant change in what's in the Python distributions and how things are linked, so it might have some unexpected side effects.)
> > As mentioned above I think the "Can't find a usable init.tcl" problem was solved previously in December... but please try the same update instructions and see if it's fixed :)
> 
> Confirmed! Tried 3.11 & 3.12 - verified that my program still was crashing before doing the reinstall but after upgrading with `--reinstall` it works (although there is some issues with corner rounding on elements, but not necessarily related to this issue). Awesome! 🙏

Same here. WSL2 on Windows 11. python 3.11 & 3.12 not working.
